import {
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Brain,
  Building2,
  Calendar,
  ClipboardList,
  Code2,
  Coffee,
  CreditCard,
  Database,
  Eye,
  FileText,
  Filter,
  FlaskConical,
  Globe,
  HeartPulse,
  Layers,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  Package,
  Plane,
  Receipt,
  Recycle,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Truck,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/data/types";

const icons: Record<IconName, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  package: Package,
  users: Users,
  receipt: Receipt,
  chart: BarChart3,
  shield: ShieldCheck,
  "file-text": FileText,
  brain: Brain,
  bot: Bot,
  message: MessageSquare,
  database: Database,
  workflow: Workflow,
  globe: Globe,
  store: Store,
  "shopping-bag": ShoppingBag,
  code: Code2,
  "heart-pulse": HeartPulse,
  sprout: Sprout,
  recycle: Recycle,
  truck: Truck,
  plane: Plane,
  building: Building2,
  rocket: Rocket,
  stethoscope: Stethoscope,
  flask: FlaskConical,
  "credit-card": CreditCard,
  bell: Bell,
  search: Search,
  calendar: Calendar,
  "map-pin": MapPin,
  sparkles: Sparkles,
  filter: Filter,
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  layers: Layers,
  boxes: Boxes,
  clipboard: ClipboardList,
  eye: Eye,
  settings: Settings,
  zap: Zap,
};

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.6} {...props} />;
}
